baseURL = "https://nitinsharmacs.github.io"
languageCode = 'en-us'
title = 'bitPhile'
theme = "PaperMod"
googleAnalytics = 'gJLtPY-9n93JySFcqJqqBbytVUMKY7nTN5ZTvTmOfjY'

[[socialIcons]]
name = "github"
url = "https://github.com/nitinsharmacs"

